const Esktrakurikuler = [
  {
    id: "K001",
    name: "Bahasa Jepang",
    rules: [
      {
        jenisKegiatan: { jenisKegiatanId: "JK01", jenisKegiatanName: "Akademik" },
        sifatKegiatan: { sifatKegiatanId: 'SK02', sifatKegiatanName: "Individual"},
        lokasiKegiatan: { lokasiKegiatanId: 'LK01', lokasiKegiatanName: "Indoor"},
        frekuensiKegiatan: { frekuensiKegiatanId: 'FRK02', frekuensiKegiatanName: "2x Seminggu"},
        aktivitasKegiatan: { aktivitasKegiatanId: 'AK02', aktivitasKegiatanName: "Latihan"},
        fokusKegiatan: { fokusKegiatanId: 'FOK03', fokusKegiatanName: "Keduanya"},
        waktuKegiatan: { waktuKegiatanId: 'WK01', waktuKegiatanName: "Weekdays"},

      },
    ],
  },
];


const KategoriKegiatan = [
    {
        id: 'JK01',
        kode: 'JK',
        jenisKegiatan: 'Akademik',
        namaKegiatan:['K001', 'K015']

    },

    {
        id: 'JK02',
        kode: 'JK',
        jenisKegiatan: 'Olahraga',
        namaKegiatan:['K002', 'K003']
    },

    {
        id: 'JK03',
        kode: 'JK',
        jenisKegiatan: 'Olahraga',
        namaKegiatan:['K002', 'K003']
    },

    {
        id: 'JK02',
        kode: 'JK',
        jenisKegiatan: 'Olahraga',
        namaKegiatan:['K002', 'K003']
    },




]